#!/bin/bash
# Read username and password
read -r -p "username: " username
read -r -s -p "password: " password

# substitute into the curl command
curl -i -H "Content-Type: application/json" \
	-X POST -d '{"username": "'$username'", "password": "'$password'"}' \
	-c cookie-jar -k https://localhost:5000/login
