DELIMITER //
DROP TABLE IF EXISTS feedback //
CREATE TABLE feedback (
 USER_ID   VARCHAR(50)  NOT NULL,
 FEEDBACK_CODE   INT	NOT NULL AUTO_INCREMENT,
 FEEDBACK VARCHAR(255) NOT NULL,
 DATE_CREATED DATETIME  DEFAULT CURRENT_TIMESTAMP,
 LAST_MODIFIED DATETIME  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (NAME_CODE, USER_ID),
 FOREIGN KEY (USER_ID) REFERENCES user(USER_NAME)
)//
DELIMITER ;
