DROP TABLE IF EXISTS first_name;
CREATE TABLE first_name (
  FIRST_CODE		INT         NOT NULL AUTO_INCREMENT,
  FIRST_NAME		VARCHAR(50) NOT NULL,
  GENDER			VARCHAR(50) NOT NULL,
  BACKGROUND		VARCHAR(50)	NOT NULL,
  DATE_CREATED		DATETIME	DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED		DATETIME	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (FIRST_CODE)
);

ALTER TABLE first_name
ADD CONSTRAINT unique_first_name UNIQUE (FIRST_NAME, GENDER, BACKGROUND);