DROP TABLE IF EXISTS last_name;
CREATE TABLE last_name (
  LAST_CODE			INT         NOT NULL AUTO_INCREMENT,
  LAST_NAME			VARCHAR(50) NOT NULL,
  GENDER			VARCHAR(50) NOT NULL,
  BACKGROUND		VARCHAR(50)	NOT NULL,
  DATE_CREATED		DATETIME	DEFAULT CURRENT_TIMESTAMP,
  LAST_MODIFIED		DATETIME	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (LAST_CODE)
);

ALTER TABLE last_name
ADD CONSTRAINT unique_last_name UNIQUE (LAST_NAME, GENDER, BACKGROUND);