DROP TABLE IF EXISTS middle_name;
CREATE TABLE middle_name (
  MIDDLE_CODE			INT         NOT NULL AUTO_INCREMENT,
  MIDDLE_NAME			VARCHAR(50) NOT NULL,
  GENDER				VARCHAR(50) NOT NULL,
  BACKGROUND			VARCHAR(50)	NOT NULL,
  DATE_CREATED			DATETIME	DEFAULT CURRENT_TIMESTAMP,
  MIDDLE_MODIFIED		DATETIME	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (MIDDLE_CODE)
);

ALTER TABLE middle_name
ADD CONSTRAINT unique_middle_name UNIQUE (MIDDLE_NAME, GENDER, BACKGROUND);