DELIMITER //
DROP TABLE IF EXISTS saved_name //
CREATE TABLE saved_name (
 USER_ID   VARCHAR(50)  NOT NULL,
 NAME_CODE   INT          NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(255) NOT NULL,
 GENDER   VARCHAR(50)  NOT NULL,
 BACKGROUND  VARCHAR(50)  NOT NULL,
 DATE_CREATED DATETIME  DEFAULT CURRENT_TIMESTAMP,
 LAST_MODIFIED DATETIME  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (NAME_CODE, USER_ID),
 FOREIGN KEY (USER_ID) REFERENCES user(USER_NAME)
)//
DELIMITER ;
