DROP TABLE IF EXISTS user;
CREATE TABLE user (
  USER_ID 		INT         NOT NULL AUTO_INCREMENT,
  USER_NAME     VARCHAR(50) UNIQUE NOT NULL,
  PASSWORD		VARCHAR(255) NOT NULL,
  EMAIL			VARCHAR(150) NOT NULL,
  IS_ADMIN		BOOLEAN		NOT NULL DEFAULT FALSE,
  PRIMARY KEY (USER_ID)
);